# Generated by Django 3.2.9 on 2021-11-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0002_auto_20211126_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagePost',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='image/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ratownicy_blog.post')),
            ],
        ),
    ]
