# Generated by Django 3.2.9 on 2021-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0004_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('statisticsImage', models.FileField(upload_to='statistics/')),
            ],
        ),
    ]
