# Generated by Django 3.2.9 on 2021-11-29 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0005_statisticsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsimage',
            name='statisticsPublished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
