# Generated by Django 3.2.9 on 2021-11-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0006_statisticsimage_statisticspublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('szkolenia', 'Szkolenia'), ('podstawowe', 'Podstawowe')], default='podstawowe', max_length=11),
        ),
    ]
