# Generated by Django 3.2.9 on 2021-12-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0007_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsimage',
            name='title',
        ),
    ]
