# Generated by Django 3.2.9 on 2022-02-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0011_infosection_infosectiondetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
