# Generated by Django 3.2.9 on 2022-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratownicy_blog', '0012_auto_20220213_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionTitle', models.CharField(max_length=255)),
            ],
        ),
    ]
